# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 59ffc33b00f6778ac3ffc8f5d79147e28a7afc844974a9660a64ebc25a19d408804ad0d41a5a8f437787d6206725c4c78b83ed24bb4dfd5ced061cc8fb5a1b61

test:
  secret_key_base: 46c64718914cfc9d5494056e991e15d6d9848a61bce03c456a53bc36b3de1e022a9df6376a9dac378708db8559845eb54e931ff2162aa7a38b001e82795c804b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
